# Generated by Django 6.0.7 on 2026-07-30 10:21

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_tools_stats", "0023_alter_criteriatostatsm2m_choices_based_on_time_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedvalue",
            name="operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Count", "Count"),
                    ("Sum", "Sum"),
                    ("Avg", "Avgerage"),
                    ("Median", "Median"),
                    ("AvgCountPerInstance", "Avgerage count per active model instance"),
                    ("Max", "Max"),
                    ("Min", "Min"),
                    ("StdDev", "StdDev"),
                    ("Variance", "Variance"),
                ],
                max_length=90,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardstats",
            name="allowed_type_operation_field_name",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Count", "Count"),
                    ("Sum", "Sum"),
                    ("Avg", "Avgerage"),
                    ("Median", "Median"),
                    ("AvgCountPerInstance", "Avgerage count per active model instance"),
                    ("Max", "Max"),
                    ("Min", "Min"),
                    ("StdDev", "StdDev"),
                    ("Variance", "Variance"),
                ],
                help_text="More than one selected field will display chooser on the chart.",
                max_length=1000,
                null=True,
                verbose_name="Choose Type operation",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardstats",
            name="type_operation_field_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Count", "Count"),
                    ("Sum", "Sum"),
                    ("Avg", "Avgerage"),
                    ("Median", "Median"),
                    ("AvgCountPerInstance", "Avgerage count per active model instance"),
                    ("Max", "Max"),
                    ("Min", "Min"),
                    ("StdDev", "StdDev"),
                    ("Variance", "Variance"),
                ],
                help_text="Choose the type operation what you want to aggregate.",
                max_length=90,
                null=True,
                verbose_name="Choose Type operation",
            ),
        ),
    ]
