# Generated by Django 6.0.7 on 2026-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoproject", "0004_testkid_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="testkid",
            name="pocket_money",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
